spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    username: root
    password: heyufeng
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      table-prefix: t_
      id-type: auto

  type-aliases-package: com.shamengxin.mybatisplus.pojo
  type-enums-package: com.shamengxin.mybatisplus.enums

#多数据源配置
#spring:
#  #配置数据源信息
#  datasource:
#    dynamic:
#      # 设置默认的数据源或者数据源组,默认值即为master
#      primary: master
#      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
#      strict: false
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: 123456
#        slave_1:
#          url: jdbc:mysql://localhost:3306/mybatis_plus_1?characterEncoding=utf-8&useSSL=false
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: 123456